services:
  keycloak-postgres:
    container_name: keycloak-postgres
    image: postgres:15.3
    volumes:
      - D:/Backend/Docker_Volumes/ecommerce-microservices/api-gateway/postgres_keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - D:/Backend/Docker_Volumes/ecommerce-microservices/api-gateway/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-postgres