spring.application.name=order-service

spring.datasource.url=${DB_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
server.port=8087

inventory.service.url=http://localhost:8088

spring.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html